use_frameworks!

# 通过pod 使用三方库时,必须指定明确的版本号!方便同期开发的用户使用相同的三方,方便后续更新!
# 编辑该文件时,必须使用专业的编辑器.不允许使用记事本编辑,避免导致的乱码错误引发的问题.

target 'AiLiToolbox_Tests' do
  pod 'AiLiToolbox', :path => '../'         # 工具集

  # 测试相关
  pod 'Quick', '1.1.0'                      # TDD 框架
  pod 'Nimble', '5.1.1'                     # 断言框架
  pod 'Mockingjay', '2.0.0'                 # 网络请求模拟

end
